---
ID: "16861d00-d787-45ac-96e6-549a18dc2e77"
Parent: "2c784361-01fe-4572-8cd4-08add6d16cfb"
Template: "2c784361-01fe-4572-8cd4-08add6d16cfb"
Path: /sitecore/templates/Feature/Navigation/Rendering Parameters/Weather Drawer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d03a1ec0-870b-44a3-a303-ede95e4c8269"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240610T081045Z
