---
ID: "5e584709-ff8d-403a-8c03-45057c2c8908"
Parent: "67eaf642-85bc-460e-8ec2-41727a0e0bf6"
Template: "67eaf642-85bc-460e-8ec2-41727a0e0bf6"
Path: /sitecore/templates/Project/KKIA/Page Content/Faq/Faq Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{958FB056-E4C6-4953-88D1-1BD4599FE3D9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240829T081336Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fdef1b03-20f6-4ba3-9b40-44c7807460a5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T081405Z
