---
ID: "77b71f3e-74b5-4c5b-909f-a5846bb720e8"
Parent: "a07e9ce5-8473-4488-930d-f88275dddf0a"
Template: "a07e9ce5-8473-4488-930d-f88275dddf0a"
Path: /sitecore/templates/Project/KKIA/Page Content/Hero Slider/Container/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{207B3CC0-35ED-401C-843E-DF04A5C23C6F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240620T114947Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53488d77-e668-4972-a36e-55cf995032b3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240620T115231Z
