---
ID: "3ffcff7e-8d0e-4dec-b319-93708b4d7927"
Parent: "6f0d2003-d7a2-4c32-a09b-00b516cebf42"
Template: "6f0d2003-d7a2-4c32-a09b-00b516cebf42"
Path: /sitecore/templates/Feature/Navigation/Rendering Parameters/Logo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3f893683-93e2-46f6-816b-b6cb7503e4a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240610T085835Z
