---
ID: "fbd677b9-9d45-41a0-b822-a67f6c0478f8"
Parent: "55615615-4644-47a8-9049-8d21458427ed"
Template: "55615615-4644-47a8-9049-8d21458427ed"
Path: /sitecore/templates/Project/KKIA/Services/Banking Services/Banking Services Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240905T064319Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4e428ba-b136-4a9e-b7fe-d22f0b2dcac0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240923T104137Z
    - ID: "e264db3b-245b-4f76-9cae-37ac77a41548"
      Hint: Title
      Value: $name
