/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      boxShadow: {
        default: '0px 2px 4px 0px rgba(60, 60, 59, 0.06)',
        hover: '0px 4px 24px 0px rgba(60, 60, 59, 0.08)',
        pressed: '0px 4px 8px 0px rgba(60, 60, 59, 0.16)',
        'blur-rough': '0px 4px 4px 0px rgba(60, 60, 59, 0.25)',
        'blur-hover': '0px 4px 4px 0px rgba(60, 60, 59, 0.25)',
        'blur-soft': '0px 2px 4px 0px rgba(60, 60, 59, 0.06)',
        outline: '0 0 0 2px var(--border-action-focus)',
        'outline-invert': '0 0 0 2px var(--border-action-focus-invert)',
      },
      blur: {
        rough: '8px',
        hover: '4px',
        soft: '4px',
      },
      backgroundImage: {
        'blue-overlay': 'linear-gradient(to bottom, #16477200, #164772A3, #164772)',
        'blue-overlay-2': 'linear-gradient(0deg, #2574BB 0%, #2574BB 50%, #2574BB 100%)',
        'blue-overlay-3': 'linear-gradient(to bottom, #2574BB00, #2574BB )',
        'about-background': "url('/images/6.jpeg')",
        'footer-top-bg': 'linear-gradient(0deg, #1F619B 50%,  #FFFFFF 50%)',
        
      },
      fontWeight: {
        light: 300,
        normal: 400,
        semibold: 700,
        black: 900,
      },
      colors: {
        // Background
        background: 'var(--background)',

        // Text
        'text-invert': 'var(--text-invert)',
        'text-action-invert': 'var(--text-action-invert)',
        'text-action-disabled': 'var(--text-action-disabled)',
        'text-info': 'var(--text-info)',
        'text-error': 'var(--text-error)',
        'text-warning': 'var(--text-warning)',
        'text-success': 'var(--text-success)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-action-primary': 'var(--text-action-primary)',
        'text-action-secondary-default': 'var(--text-action-secondary-default)',
        'text-action-tertiary-default': 'var(--text-action-tertiary-default)',
        'text-action-invert-default': 'var(--text-action-invert-default)',
        'text-action-invert-hover': 'var(--text-action-invert-hover)',
        'text-action-invert-press': 'var(--text-action-invert-press)',

        // Border
        'border-primary': 'var(--border-primary)',
        'border-action-primary-default': 'var(--border-action-primary-default)',
        'border-action-primary-hover': 'var(--border-action-primary-hover)',
        'border-action-primary-press': 'var(--border-action-primary-press)',
        'border-action-secondary-default': 'var(--border-action-secondary-default)',
        'border-action-secondary-hover': 'var(--border-action-secondary-hover)',
        'border-action-secondary-press': 'var(--border-action-secondary-press)',
        'border-action-tertiary-default': 'var(--border-action-tertiary-default)',
        'border-action-tertiary-hover': 'var(--border-action-tertiary-hover)',
        'border-action-tertiary-press': 'var(--border-action-tertiary-press)',
        'border-action-disabled': 'var(--border-action-disabled)',
        'border-action-focus': 'var(--border-action-focus)',
        'border-action-invert-default': 'var(--border-action-invert-default)',
        'border-action-invert-hover': 'var(--border-action-invert-hover)',
        'border-action-invert-press': 'var(--border-action-invert-press)',

        // Surface
        'surface-secondary-invert': 'var(--surface-secondary-invert)',
        'surface-action-primary-default': 'var(--surface-action-primary-default)',
        'surface-action-primary-hover': 'var(--surface-action-primary-hover)',
        'surface-action-primary-press': 'var(--surface-action-primary-press)',
        'surface-action-secondary-default': 'var(--surface-action-secondary-default)',
        'surface-action-secondary-hover': 'var(--surface-action-secondary-hover)',
        'surface-action-secondary-press': 'var(--surface-action-secondary-press)',
        'surface-action-tertiary-default': 'var(--surface-action-tertiary-default)',
        'surface-action-tertiary-hover': 'var(--surface-action-tertiary-hover)',
        'surface-action-tertiary-press': 'var(--surface-action-tertiary-press)',
        'surface-primary': 'var(--surface-primary)',
        'surface-secondary': 'var(--surface-secondary)',
        'surface-secondary-2': 'var(--surface-secondary-2)',
        'surface-quaternary': 'var(--surface-quaternary)',
        'surface-error': 'var(--surface-error)',
        'surface-info': 'var(--surface-info)',
        'surface-warning': 'var(--surface-warning)',
        'surface-success': 'var(--surface-success)',
        'surface-action-disabled': 'var(--surface-action-disabled)',
        'surface-on-action-disabled': 'var(--surface-on-action-disabled)',

        // Icon
        'icon-primary': 'var(--icon-primary)',
        'icon-action-primary': 'var(--icon-action-primary)',
        'icon-action-secondary-default': 'var(--icon-action-secondary-default)',
        'icon-action-secondary-hover': 'var(--icon-action-secondary-hover)',
        'icon-action-secondary-press': 'var(--icon-action-secondary-press)',
        'icon-error': 'var(--icon-error)',
        'icon-info': 'var(--icon-info)',
        'icon-warning': 'var(--icon-warning)',
        'icon-success': 'var(--icon-success)',
        'icon-action-disabled': 'var(--icon-action-disabled)',

        // Additional
        'aqua-700': 'var(--aqua-700)',

        'ocean-50': 'var(--ocean-50)',
        'ocean-100': 'var(--ocean-100)',
        'ocean-200': 'var(--ocean-200)',
        'ocean-300': 'var(--ocean-300)',
        'ocean-400': 'var(--ocean-400)',
        'ocean-500': 'var(--ocean-500)',
        'ocean-600': 'var(--ocean-600)',
        'ocean-700': 'var(--ocean-700)',
        'ocean-800': 'var(--ocean-800)',

        'indigo-50': 'var(--indigo-50)',
        'indigo-100': 'var(--indigo-100)',
        'indigo-300': 'var(--indigo-300)',
        'indigo-400': 'var(--indigo-400)',
        'indigo-500': 'var(--indigo-500)',
        'indigo-600': 'var(--indigo-600)',

        'grayscale-0': 'var(--grayscale-0)',
        'grayscale-50': 'var(--grayscale-50)',
        'grayscale-100': 'var(--grayscale-100)',
        'grayscale-200': 'var(--grayscale-200)',
        'grayscale-300': 'var(--grayscale-300)',
        'grayscale-400': 'var(--grayscale-400)',
        'grayscale-500': 'var(--grayscale-500)',
        'grayscale-600': 'var(--grayscale-600)',
        'grayscale-700': 'var(--grayscale-700)',
        'grayscale-800': 'var(--grayscale-800)',
        'grayscale-900': 'var(--grayscale-900)',

        'error-50': 'var(--error-50)',
        'error-100': 'var(--error-100)',
        'error-200': 'var(--error-200)',
        'error-300': 'var(--error-300)',
        'error-400': 'var(--error-400)',
        'error-500': 'var(--error-500)',

        'warning-50': 'var(--warning-50)',
        'warning-100': 'var(--warning-100)',
        'warning-200': 'var(--warning-200)',
        'warning-300': 'var(--warning-300)',
        'warning-400': 'var(--warning-400)',
        'warning-500': 'var(--warning-500)',
        'warning-600': 'var(--warning-600)',

        'info-50': 'var(--info-50)',
        'info-100': 'var(--info-100)',
        'info-200': 'var(--info-200)',
        'info-300': 'var(--info-300)',
        'info-400': 'var(--info-400)',
        'info-500': 'var(--info-500)',

        'success-50': 'var(--success-50)',
        'success-100': 'var(--success-100)',
        'success-200': 'var(--success-200)',
        'success-300': 'var(--success-300)',
        'success-400': 'var(--success-400)',
        'success-500': 'var(--success-500)',
      },
      fontFamily: {
        frutiger: ['var(--font-frutiger)'],
      },
    },
  },
  plugins: [],
};
