---
ID: "4d1d7e27-fdd2-4ef9-ba50-601bf46678b5"
Parent: "f4cc43de-a034-497b-a00c-772f79f92dc6"
Template: "f4cc43de-a034-497b-a00c-772f79f92dc6"
Path: /sitecore/templates/Feature/Navigation/Rendering Parameters/Main Navigation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcb204af-1dba-484f-b34f-a25d4d2c977d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240612T100406Z
