---
ID: "5dd9aab1-f4eb-4867-9d75-0e906b74992b"
Parent: "ae3f9174-d6bf-42e9-84b3-5c511b0587e0"
Template: "ae3f9174-d6bf-42e9-84b3-5c511b0587e0"
Path: /sitecore/templates/Project/KKIA/Parking and Transport/Address Banner/Address Banner Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{8882F30D-5B53-4D75-AF64-F00184A6089B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240905T064327Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "27678290-6c6a-434b-ab23-703b73b521d9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240905T064345Z
