---
ID: "2c3be86e-1552-4dce-8aa5-e509f7aa11b1"
Parent: "9c31096b-4e1f-46d8-b1ad-82fe6fbcdb43"
Template: "9c31096b-4e1f-46d8-b1ad-82fe6fbcdb43"
Path: /sitecore/templates/Project/KKIA/Flights/Destinations and Airlines/Airline Details/Page Hero/Airline Page Hero Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6F14F2E1-F340-45A6-AA12-D8AC869F333F}
    {9C31096B-4E1F-46D8-B1AD-82FE6FBCDB43}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "896edf04-7b0d-47de-af02-f087dcbcf6d5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240826T081552Z
