---
ID: "70e1266c-df9a-40e4-bca6-7ffb2055a1d9"
Parent: "86ecaa2f-5add-4639-a8f1-179a4319d87b"
Template: "86ecaa2f-5add-4639-a8f1-179a4319d87b"
Path: /sitecore/templates/Project/KKIA/Page Content/Rendering Parameters/Terminal Tabs/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "563264c4-040f-4427-8c3c-6745bcde8201"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240909T062817Z
