---
ID: "45966f2e-b2a1-49fc-a41d-efd44d467300"
Parent: "a09b0503-1860-4c63-b826-13757c89698a"
Template: "a09b0503-1860-4c63-b826-13757c89698a"
Path: /sitecore/templates/Project/KKIA/Services/Service Classes Cards/Services Classes Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240905T064319Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "712db92f-ea23-41fc-9830-4fd7c467c1cb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240929T114525Z
    - ID: "ecec4084-078a-457c-83ec-1dca3ad992c7"
      Hint: Title
      Value: $name
