// This component was generated by @sitecore-search/cli on Thu Oct 24 2024 17:45:04 GMT+0200 (czas środkowoeuropejski letni)

import { CheckIcon } from '@radix-ui/react-icons';
import type { SearchResponseFacet } from '@sitecore-search/react';
import { useSearchResultsActions } from '@sitecore-search/react';
import {
  AccordionFacets,
  FacetItem,
  RangeFacet,
  SearchResultsAccordionFacets,
  SearchResultsFacetValueRange,
} from '@sitecore-search/ui';

type PriceFacetProps = {
  min: number;
  max: number;
};

const PriceFacet = ({ min, max }: PriceFacetProps) => {
  return (
    <SearchResultsFacetValueRange
      max={max}
      min={min}
      autoAdjustValues={false}
      className="relative flex items-center w-full h-5 mb-8 select-none touch-none"
    >
      <RangeFacet.Track className="relative grow h-[3px] rounded-full bg-gray-400">
        <RangeFacet.Range className="absolute h-full bg-gray-700 rounded-full" />
      </RangeFacet.Track>
      <RangeFacet.Start className="block w-5 h-5 bg-[white] shadow-[0_2px_10px_grey] text-[10px] leading-5 text-center cursor-pointer rounded-[10px] hover:bg-gray-700 focus:shadow-[0_0_0_3px_grey]">
        {(value) => <span className="absolute text-sm left-0 top-[30px]">${value}</span>}
      </RangeFacet.Start>
      <RangeFacet.End className="block w-5 h-5 bg-[white] shadow-[0_2px_10px_grey] text-[10px] leading-5 text-center cursor-pointer rounded-[10px] hover:bg-gray-700 focus:shadow-[0_0_0_3px_grey]">
        {(value) => <span className="absolute text-sm left-0 top-[30px]">${value}</span>}
      </RangeFacet.End>
    </SearchResultsFacetValueRange>
  );
};

type SearchFacetsProps = {
  facets: SearchResponseFacet[];
};

const SearchFacets = ({ facets }: SearchFacetsProps) => {
  const { onFacetClick } = useSearchResultsActions();
  return (
    <SearchResultsAccordionFacets
      defaultFacetTypesExpandedList={[]}
      // onFacetTypesExpandedListChange={() => {}}
      onFacetValueClick={onFacetClick}
      className="w-full"
    >
      {facets.map((f) => (
        <AccordionFacets.Facet
          facetId={f.name}
          key={f.name}
          className="block pb-4 mb-4 border-b border-gray-200 dark:border-gray-600"
        >
          <AccordionFacets.Header className="flex">
            <AccordionFacets.Trigger className="text-sm font-semibold md:text-base focus:outline-gray-700">
              {f.label}
            </AccordionFacets.Trigger>
          </AccordionFacets.Header>
          <AccordionFacets.Content className="mt-8">
            {f.name !== 'price' ? (
              <AccordionFacets.ValueList className="flex flex-col mt-2 space-y-2 list-none">
                {f.value.map((v, index: number) => (
                  <FacetItem
                    {...{
                      index,
                      facetValueId: v.id,
                    }}
                    key={v.id}
                    className="flex items-center text-sm cursor-pointer group"
                  >
                    <AccordionFacets.ItemCheckbox className="flex-none w-5 h-5 transition duration-500 ease-in-out border border-gray-300 rounded cursor-pointer form-checkbox hover:border-heading focus:outline-gray-700 aria-checked:bg-gray-700 aria-checked:hover:bg-heading aria-checked:focus:bg-heading">
                      <AccordionFacets.ItemCheckboxIndicator className="w-5 h-5 text-white ">
                        <CheckIcon />
                      </AccordionFacets.ItemCheckboxIndicator>
                    </AccordionFacets.ItemCheckbox>
                    <AccordionFacets.ItemLabel className="text-sm ms-4 -mt-0.5">
                      {v.text} {v.count && `(${v.count})`}
                    </AccordionFacets.ItemLabel>
                  </FacetItem>
                ))}
              </AccordionFacets.ValueList>
            ) : (
              <PriceFacet
                min={Math.floor(f.value[0].min)}
                max={Math.floor(f.value[f.value.length - 1].max)}
              />
            )}
          </AccordionFacets.Content>
        </AccordionFacets.Facet>
      ))}
    </SearchResultsAccordionFacets>
  );
};

export default SearchFacets;
