---
ID: "579c22c9-e918-4efa-b5cb-97d2113a008f"
Parent: "f7d0fd12-c116-44ff-97ab-c7c213be01a3"
Template: "f7d0fd12-c116-44ff-97ab-c7c213be01a3"
Path: /sitecore/templates/Project/KKIA/Page Content/Places Card Slider/Places Card Slider/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{2C50C368-3B48-4116-A082-F32F9075D772}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240819T142447Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c12e8961-de9f-4d4a-9e20-f7d38e4e091f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpiestov@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240819T142509Z
