---
ID: "a6fa6932-8271-4787-8404-927539fc6034"
Parent: "a3ae8d01-ada3-4c40-844f-85304091338a"
Template: "a3ae8d01-ada3-4c40-844f-85304091338a"
Path: /sitecore/templates/Project/KKIA/Flights/Destinations and Airlines/Airlines List/Airlines List/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240903T104954Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4884cc3-454b-4336-b011-fd0ca2d9075e"
    - ID: "b581acb0-9b86-46a1-adbb-0329ae89e0ca"
      Hint: Button Text
      Value: View more
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240906T083134Z
