---
ID: "fbecd35b-ff05-44fb-bb50-aa8d67aaf5f1"
Parent: "eea3f107-5ddd-452c-b8a8-7cfd5628baff"
Template: "eea3f107-5ddd-452c-b8a8-7cfd5628baff"
Path: /sitecore/templates/Project/KKIA/Page Content/Image with Tile Slider/Image with Tile Slider/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{459C041B-E6EC-4ECF-8208-66237736A8E1}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240927T071908Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b74fad13-35ab-4469-9dad-ab2ad55d7243"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240927T072033Z
