---
ID: "d8ad0214-b899-47aa-9ad1-c55e37b4e2be"
Parent: "c248ce6f-6db8-4131-93e4-dde3fa10fdce"
Template: "c248ce6f-6db8-4131-93e4-dde3fa10fdce"
Path: /sitecore/templates/Feature/Navigation/Rendering Parameters/Language Drawer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1e76a257-ddde-471e-8128-bc6b741b737f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240611T080630Z
