---
ID: "6cdebd8e-5244-469e-8263-4de1198e4a65"
Parent: "78f35239-baef-4508-8695-1f07b1f271f6"
Template: "78f35239-baef-4508-8695-1f07b1f271f6"
Path: /sitecore/templates/Project/KKIA/Shop Dine Explore/Three Column Shops/Three Column Shops/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240903T104954Z
    - ID: "3d372323-c6a2-4aa6-8891-159a3abc9cc6"
      Hint: Button Text
      Value: View more
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "05dca198-25a9-44ad-a0a7-288221dda41f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240903T105000Z
