---
ID: "36a58868-4e95-4b0a-863a-705fd071dcb1"
Parent: "c49e9f8a-9b4e-4402-bb10-f9624242f233"
Template: "c49e9f8a-9b4e-4402-bb10-f9624242f233"
Path: /sitecore/templates/Project/KKIA/Flights/Destinations and Airlines/Airline Details/Airline Details 3 Columns/Airline Details 3 Columns/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240724T084315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "63536e46-eadb-4592-9fad-2419c4f6f7fc"
      Hint: Airline
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2bcf382e-3cdc-4e19-a231-16637726a87b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240826T092149Z
