/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      backgroundImage: {
        'green-overlay': `linear-gradient(0deg, rgba(29, 29, 29, 0.25), rgba(29, 29, 29, 0.25)),
                            linear-gradient(13.74deg, #1E514F 8.13%, rgba(22, 86, 83, 0.675205) 46.83%, rgba(5, 97, 92, 0) 90.96%)`,
        'green-overlay-2': 'linear-gradient(to bottom, #1E514F 100%, #125956 50%, #05615C 0%)',
      },
      margin: {
        custom: 'max(0px, (100vw - 1320px) / 2)',
        custom2: 'max(0px, (90% - 1320px) / 2)',
      },
      fontFamily: {
        frutiger: ['var(--font-frutiger)'],
      },
      fontWeight: {
        light: 300,
        normal: 400,
        semibold: 700,
        black: 900,
      },
      colors: {
        darkGreen: 'var(--dark-green)',
        background: 'var(--background)',
        'background-variant': 'var(--background-variant)',
        'background-dark': 'var(--background-dark)',
        'background-gray-variant': 'var(--background-gray-variant)',
        info: 'var(--info)',
        'info-border': 'var(--info-border)',
        'info-light': 'var(--info-light)',
        lightGray: 'var(--jade-light)',
        lightGray2: 'var(--background-dark)',
        lightGreen: 'var(--primary-variant)',
        lightGreen3: 'var(--primary-dark-green)',
        black: 'var(--jade-darker)',
        jade: {
          light: 'var(--jade-light)',
          lighter: 'var(--jade-lighter)',
          dark: 'var(--jade-dark)',
          darker: 'var(--jade-darker)',
          darkest: 'var(--jade-darkest)',
        },
        primary: {
          'dark-green': 'var(--primary-dark-green)',
          'dark-green-variant': 'var(--primary-dark-green-variant)',
          'light-green': 'var(--primary-light-green)',
          variant: 'var(--primary-variant)',
        },
        surface: {
          'action-primary-default': 'var(--surface-action-primary-default)',
          'action-primary-hover': 'var(--surface-action-primary-hover)',
          'action-primary-press': 'var(--surface-action-primary-press)',
        },
        muted: {
          primary: 'var(--muted-primary)',
          dark: 'var(--muted-dark)',
          darkest: 'var(--muted-darkest)',
          darker: 'var(--muted-darker)',
          variant: 'var(--muted-variant)',
        },
        border: {
          light: 'var(--border-light)',
        },
        error: {
          dark: 'var(--error-dark)',
        },

        // New styles
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          invert: 'var(--text-invert)',
          error: 'var(--text-error)',
          warning: 'var(--text-warning)',
          info: 'var(--text-info)',
          success: 'var(--text-success)',
          'action-primary': 'var(--text-action-primary)',
          'action-secondary-default': 'var(--text-action-secondary-default)',
          'action-secondary-hover': 'var(--text-action-secondary-hover)',
          'action-secondary-press': 'var(--text-action-secondary-press)',
          'action-disabled': 'var(--text-action-disabled)',
        },
        border: {
          primary: 'var(--border-primary)',
          secondary: 'var(--border-secondary)',

          tertiary: 'var(--border-tertiary)',
          'action-primary-default': 'var(--border-action-primary-default)',
          'action-primary-hover': 'var(--border-action-primary-hover)',
          'action-primary-press': 'var(--border-action-primary-press)',

          'action-secondary-default': 'var(--border-action-secondary-default)',
          'action-secondary-hover': 'var(--border-action-secondary-hover)',
          'action-secondary-press': 'var(--border-action-secondary-press)',

          'action-tertiary-default': 'var(--border-action-tertiary-default)',
          'action-tertiary-hover': 'var(--border-action-tertiary-hover)',
          'action-tertiary-press': 'var(--border-action-tertiary-press)',
          'action-tertiary-filled': 'var(--border-action-tertiary-filled)',
          'action-disabled': 'var(--border-action-disabled)',
          'action-focus': 'var(--border-action-focus)',
          error: 'var(--border-error)',
        },
        surface: {
          primary: 'var(--surface-primary)',
          secondary: 'var(--surface-secondary)',
          'secondary-invert': 'var(--surface-secondary-invert)',
          quaternary: 'var(--surface-quaternary)',
          'action-primary-default': 'var(--surface-action-primary-default)',
          'action-primary-hover': 'var(--surface-action-primary-hover)',
          'action-primary-press': 'var(--surface-action-primary-press)',
          'action-secondary-default': 'var(--surface-action-secondary-default)',
          'action-secondary-hover': 'var(--surface-action-secondary-hover)',
          'action-secondary-press': 'var(--surface-action-secondary-press)',
          'action-tertiary-default': 'var(--surface-action-tertiary-default)',
          'action-tertiary-hover': 'var(--surface-action-tertiary-hover)',
          'action-tertiary-press': 'var(--surface-action-tertiary-press)',
          'action-tertiary-filled': 'var(--surface-action-tertiary-filled)',
          'on-action-disabled': 'var(--surface-on-action-disabled)',
          disabled: 'var(--surface-disabled)',
          error: 'var(--surface-error)',
          warning: 'var(--surface-warning)',
          info: 'var(--surface-info)',
          success: 'var(--surface-success)',
        },
        icon: {
          primary: 'var(--icon-primary)',
          secondary: 'var(--icon-secondary)',
          error: 'var(--icon-error)',
          warning: 'var(--icon-warning)',
          info: 'var(--icon-info)',
          success: 'var(--icon-success)',
          invert: 'var(--icon-invert)',
          'action-secondary-default': 'var(--icon-action-secondary-default)',
          'action-secondary-hover': 'var(--icon-action-secondary-hover)',
          'action-secondary-press': 'var(--icon-action-secondary-press)',
        },
      },
      boxShadow: {
        common: '0px 2px 4px 0px #3C3C3B0F',
        arrows: '0 6px 16px 0 #3c3c3b29',
        default: '0px 2px 4px 0px rgba(60, 60, 59, 0.06)',
        hover: '0px 4px 24px 0px rgba(60, 60, 59, 0.08)',
        pressed: '0px 4px 8px 0px rgba(60, 60, 59, 0.16)',
        'blur-rough': '0px 4px 4px 0px rgba(60, 60, 59, 0.25)',
        'blur-hover': '0px 4px 4px 0px rgba(60, 60, 59, 0.25)',
        'blur-soft': '0px 2px 4px 0px rgba(60, 60, 59, 0.06)',
        outline: '0 0 0 3px var(--border-action-focus)',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('tailwindcss-rtl')],
};
