---
ID: "e7f224e4-09cf-4bbe-915e-c9333e09bbf1"
Parent: "a8bf7aec-96c6-4db6-8e4c-3f184a9215a7"
Template: "a8bf7aec-96c6-4db6-8e4c-3f184a9215a7"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Rendering Parameters/Logo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb6cb7b0-d6c2-4e91-98a6-68b3330cc7e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240605T133302Z
