---
ID: "2edba95e-30f8-43eb-bcff-a6cc1c1c8cec"
Parent: "6a3406ec-e080-4a5a-b0e6-78a2b4e6f726"
Template: "6a3406ec-e080-4a5a-b0e6-78a2b4e6f726"
Path: /sitecore/templates/Project/KKIA/Page Content/Flight Search Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B7110B15-2AFE-4D48-B458-160F038B1166}
    {6A3406EC-E080-4A5A-B0E6-78A2B4E6F726}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240625T061315Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "958c289e-2e6f-4628-aebd-5998acda2337"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mkalisz@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240625T061411Z
