---
ID: "dafb1107-9e69-44fe-86e3-0fafbe9113ca"
Parent: "96ea7919-08ce-48af-9b2d-3e87c4c593d8"
Template: "96ea7919-08ce-48af-9b2d-3e87c4c593d8"
Path: /sitecore/templates/Project/KKIA/Parking and Transport/Rendering Parameters/Parking Information Grid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b4427d7c-e596-42b3-9667-db44093bc522"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mbuczak@kogifi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240916T064417Z
